### ISSUE TITLE
UIImage on Background

### ISSUE THREAD

**Issue by ghost** [p581581/KeyboardHandler#1]
I have the following setup

UIViewController->UIView and a UIImage painted over the entire UIView.   The control has been working perfectly, but we noticed during testing that when I have a TextField close to the Top of the View that when I select it the view scrolls down beyond where the UIImage reaches - as a result I have a black bar at the top.   The problem becomes more pronounced when I look at it on an iPAD.    Any suggestions ?

Update:  upon further investigation it looks like the issue happens on the UIView as well.   I removed by image and applied a white background to my view.   See the what happens in the attached.
- BEFORE
  ![screen shot 2014-11-11 at 8 29 32 am](https://cloud.githubusercontent.com/assets/4307612/4993478/ecb67340-697c-11e4-8f4b-43b984f14080.png)
- AFTER
  ![screen shot 2014-11-11 at 8 29 47 am](https://cloud.githubusercontent.com/assets/4307612/4993477/eca41100-697c-11e4-9fa6-3ad9082c7156.png)

thanks for the great component!!

**Comment by p581581** [comment]
Hi, mdaymond.

Sorry for the late reply. About this issue, it's my fault. I already fixed this bug, but I only updated 0.0.1 branch. So, if you manually download Keyboard Handler, you could change your branch to 0.0.1, it will work perfectly, or you can use CocoaPods, it will download 0.0.1 branch automatically. Also, I'll update my master branch in the next few day. Cheers!
